export default {
en:{
  ok:"OK",
  cancel:"Cancel",
  modify:"Modify",
  remove:"Delete",
  add:"Add",
  save:"Save",
  search:"Search",
  
  flowTags:{
    //采购工作流中的按钮标签
    setPrice:'Set price',
    chkPurchase:'Check purchase list'
  },
  cfgTags:{
  },
  schTags:{
  }
},
zh:{
  ok:"确定",
  cancel:"取消",
  close:"关闭",
  modify:"修改",
  remove:"删除",
  add:"增加",
  save:"保存",
  alert:'注意',
  search:"搜索",
  confirm:"确定",
  submit:"提交",
  reject:"拒绝",
  accept:'接受',
  init:"初始化",
  clear:"清除",
  name:"名称",
  cmt:"描述",
  opr:"操作",
  apply:'申请',
  attention:'注意',
  num:"数量",
  price:'价格',

  failToCall:"调用失败",
  onlyOneType:"一次申请中，只能填写同类的申请",
  wrongFlowState:"工作流状态错乱，请确认是否清除？",
  invalidInterval:"无效的时间段",
  invalidRatio:"请输入正确的分摊比率",
  plsInputPrj:'请选择项目',
  notInBusiTime:"不在差旅的时间段内",
  hasOverlap:"时间段有重叠",
  dateFmt:"YYYY/MM/DD HH:mm",
  start:'开始时间',
  end:'结束时间',
  currency:'元',
  cfmRmv:'是否确定删除',
  flowDef:'工作流定义',
  cfgDef:'配置定义',
  schDef:'定时任务定义',
  settings:'配置',
  notOver:'尚未结束',
  sex:{
    M:"先生",
    F:"女士",
    O:"未知"
  },
  aplSta:{ //申请状态
    INIT:"初始",
    WAIT:'待确认',
    OK:'通过',
    REJ:'拒绝'
  }, 
  home:{
    attendance:"打卡",
    settings:'配置',
    tasks:'待办'
  },
  atd:{
    title:"考勤",
    clockExp:"考勤异常",
    leave:"请假",
    ovt:"加班",
    worktime:"工时申报",
    ovOrLv:'请假或加班',
    ratio:'分摊比率',
    prj:'项目',
    notChked:'未刷卡',
    
    aplType:{
      OTW:'加班',
      LEAV:'请假',
      BUSI:'工作日在途'
    },
    aplTmType:{ //时段的类型
      //WORK:'正常上下班',
      WOW:'延长工时',
      OOW:'休息日加班',
      FOW:'节假日加班',
      BUSI:'工作日在途',
      AFFA:'事假',
      SICK:'病假',
      WEAL:'福利假',
      HOLI:'年休假'
    }
  },
  crm:{
    title:'极简CRM'
  },
  resource:{
    title:'资源管理'
  },
  hr:{
    title:'人力资源',
    cfmed:'已确认',
    notCfm:'未确认',
    security:'劳动保障',

    quali:'任职资格',
    post:'任职级别',
    salary:'基本工资',
    subsidy:'出差补助',
    entryAt:'入职时间',

    holiday:'年休假(天)',
    weal:'福利假(小时)',
    sickRatio:'病假工资系数',
    fowSalary:'节假日加班工资系数',
    oowSalary:'休息日加班工资系数',
    wowSalary:'工作日加班工资系数',

    attend:'考勤方式',

    sponTp:{
      P:"个人交",
      C:"公司交"
    },
    secType:{
      R:'按比率',
      V:'按金额'
    },
    salType:{
      SALARY:'工资',
      SUBSIDY:'补贴',
      EXPENSE:'报销',
      BONUS:'奖金',
      SHARE:'分红',
      TAX:'个人所得税',
      OLD:'养老保险',
      MEDICARE:'医疗保险',
      JOB:'失业保险',
      INJURY:'工伤保险',
      PCREATION:'生育保险',
      HOUSE:'住房公积金'
    },
    eventType:{
      JOIN:'入职',
      LEAV:'离职',
      DIS:'开除',
      ADDS:'加薪',
      SUBS:'减薪',
      ASTO:'加股票',
      SSTO:'减股票',
      PROM:'升职',
      DEMO:'降职',
      UPG:'升级',
      DWG:'降级',
      FINE:'罚款',
      WARN:'警告',
      ERR:'记过',
      LAUD:'表扬',
      PRJ:'项目经历',
      OTH:'其他'
    },
    attendTp:{
      NORM:"打卡机刷卡",
      LAN:"内网打卡",
      REMO:"远程打卡",
      FREE:"不打卡"
    }
  },
  resume:{
    title:'简历',
    org:"机构",
    contrib:"贡献与收获",
    type:"性质",
    types:{
      EDU:'学校教育',
      TRA:'培训',
      PRO:'工作',
      OTH:'其他'
    }
  },
  busi:{
    title:'差旅',
    prj:'所属项目',
    reason:'事由',
    dest:'目的地',
    subsidy:'补助',
    expense:'报销',
    invoice:'发票号',
    overAt:'完成时间',
    val:'金额(元)',
    status:'审批状态',
    states:{
      INIT:'初始',
      WAIT:'等待审核',
      REJ:'被拒绝',
      RUN:'进行中',
      OVER:'结束'
    },
    
    wfSegs:[//在workflow中约定的名称
      {t:'s',n:'prjName',s:'项目'},
      {t:'s',n:'account',s:'申请人帐号'},
      {t:'s',n:'dest',s:'目的地'},
      {t:'s',n:'reason',s:'出差事由'},
      {t:'n',n:'expense',s:'报销金额'},
      {t:'n',n:'subsidy',s:'补助'},
      {t:'dt',n:'start',s:'开始时间'}, 
      {t:'dt',n:'end',s:'结束时间'},
      {t:'s',n:'cmt',s:'说明'}
    ]
  },
  purchase:{
    title:'采购',
    prj:'项目',
    buyer:'采购负责人',
    receiver:'收件人',
    applicant:'申请人',
    expDate:'期望到货日期',
    cost:'总成本(元)',
    status:'审批状态',
    sku:'存货单元',
    skuList:'采购清单',
    notCalcu:'尚未核算',
    types:{
      SELL:'向外销售',
      BUY:'向外采购',
      SELF:'内部采购'
    },
    wfSegs:[
      {t:'s',n:'prjName',s:'项目'},
      {t:'s',n:'receiver',s:'收件人'},
      {t:'n',n:'cost',s:'总成本(元)'},
      {t:'d',n:'expDate',s:'期望到货时间'},
      {t:'s',n:'applicant',s:'申请人帐号'},
      {t:'s',n:'descr',s:'附加描述'}
    ]
  },
  grn:{//goods receive notes
    title:'收货',
    state:{
        WAIT:'等待发货',
        CHK:'正在入库',
        OVER:'已完成'   
    },
    inDate:'入库时间',
    outDate:'供货方发货时间'
  },
  bal:{
    title:'报表',
    val:'金额',
    types:{
      salary:'工资',
      income:'已收款',
      pay:'已付款',
      iIncome:'内部收入',
      iPay:'内部支出',
      subsidy:'补助',
      expense:'报销',
      resource:'固定资产折旧',
      receivable:'应收账款',
      payable:'应付账款'
    }
  },
  gdn:{ //goods delivery notes
    title:'发货',
    state:{
        WAIT:'等待发货',
        CHK:'正在出库',
        TRAN:'运输中',
        OVER:'已完成',
        LOST:'丢失',
        BACK:'退货'
    },
    outDate:'出库时间',
    cfmDate:'确认时间',
    tranNo:'运单号'
  },
  my:{
    title:"我的",
    event:"关键事件",
    perm:"绩效",
    res:"资产",
    base:"基本信息",
    grp:"部门",
    startUse:'领用日期',
    now:'现在',
    moveFrom:'转自',
    moveTo:'转给',
    monSalary:'月工资明细'
  },
  prj:{
    title:'项目',
    member:'成员',
    plan:"计划",
    target:"目标",
    subPrj:'子项目',
    worktime:'工时',
    stage:"阶段",
    base:'达标值',
    challenge:'挑战值',
    real:'实际值',
    account:"帐号",
    mbrRole:'角色',
    
    type:"类型",
    start:"开始时间",
    end:"结束时间",
    realEnd:"实际结束时间",
    owner:"投资人",
    leader:"项目经理",
    scope:"范围",
    finish:"完成",
    appraise:"评价",
    cancel:"取消",
    
    typeCfg:{
      PROD:'生产',
      RND:'研发',
      HR:'人力资源',
      PUR:'采购',
      TRAI:'培训',
      SALE:'销售',
      OTH:'其他'
    },
    
    roleCfg:{
      L:"项目经理",
      O:"投资人",
      W:"普通成员"
    },
    
    stageCfg:{
      INIT:'初始',
      START:'启动',
      RUN:'进行中',
      END:'完成',
      CANC:'取消'
    },
    planSta:{
      INIT:'未完成',
      NORM:'正常完成',
      ADVA:'提前完成',
      DELA:'延迟完成',
      CANC:'取消'
    },
    targetSta:{
      INIT:'未完成',
      DONE:'完成'
    }
  },
  contacts:{
    title:'通讯录',
    level:'等级'
  },
  grp:{
    title:'群组',
    department:'部门',
    member:'成员',
    atd:'加班请假申请',
    role:{
        ADM:"经理",
        HR:"人事",
        SEC:"秘书",
        NOR:"员工", //NOR的工资才会由部门负担
        OTH:"其他"
    },
    type:{D:"部门",V:"群组"},
    struct:"组织结构",
    clockExp:"考勤异常确认",
    perf:"绩效管理",
    perfCmt:"绩效说明",
    mbrTitle:"职位",
    mbrRole:"角色",
    account:"帐号"
  },
  
  flowTags:{
    //中文使用默认的工作流标签，英文需自定义，
    //参照/assets/v3/settings/workflow.js的defaultTags
    
    //采购工作流中的按钮标签
    setPrice:'设置采购价格',
    chkPurchase:'检查采购情况'
  },
  schTags:{
    //中文使用默认的工作流标签，英文需自定义，
    //参照/assets/v3/settings/schedule.js的defaultTags
  },
  cfgTags : {
      changeNotSaved:"修改的内容尚未保存，请确认是否放弃修改？",
      needAz:'字段必须是a-z、A-Z字符的组合',
      segTypes:{'s':'文字','n':"数值",'d':'日期'},

      asMap:'模板格式',
      segKey:'字段',
      segName:"名称",
      segType:"类型",
      val:'配置内容'
  },

  //操作界面在ibf中的，返回码必须在此有定义，否则出错时不能显示合适的错误信息
  //icrm:11xxx,iresource:12xxx,ibusiness:13xxx,
  //ihr:14xxx,iproject:15xxx,ifinance:16xxx
  errMsgs:{
    12001:'出入库清单与采购申请不一致',
    12002:'采购尚未执行',

    14000:'工时未完全申报',
    14001:'已确认的工时不可更改',
    14002:"必须按整小时请假",
    14003:"年休假，必须按天请假",
    14004:"年休假余额不足",
    14005:"福利假必须按小时请",
    14006:"福利假余额不足",
    14007:"非工作时段，无需请假",
    14008:"工作时段，不可加班",
    14009:"非工作时段，无需申请在途免打卡",
    14010:"存在重复的申请",
    14011:'请假时段，不可刷卡',
    14012:'请假时段已刷卡',
    14013:'加班时段无刷卡记录',
    14014:"无效的开始结束时间段",
    14015:"超过最大忘刷卡次数",
    14016:'无有效的工时记录',
    14017:'工时不完整',
    14018:'无考勤记录',
    
    15001:"存在未完成的计划，不可结束项目",
    15002:'预置的阶段，不可删除',
    15100:'工作流已结束，不可执行此操作',
    15101:'工作流未结束，不可执行此操作'
  }
}
};