export default {
en:{
  app_name:"Operate&Manage",
  ok:"OK",
  cancel:"Cancel",
  modify:"Modify",
  remove:"Delete",
  add:"Add",
  save:"Save",
  search:"Search",
  more:"More",
},
cn:{
  ok:"确定",
  cancel:"取消",
  close:"关闭",
  modify:"修改",
  remove:"删除",
  add:"增加",
  save:"保存",
  search:"搜索",
  confirm:"确定",
  submit:"提交",
  reject:"拒绝",
  init:"初始化",
  clear:"清除",
  more:"更多",
  name:"名称",
  cmt:"描述",
  detail:"详情",
  opr:"操作",
  month:"月",
  apply:'申请',
  attention:'注意',

  oprSuccess:"操作成功",
  oprFailed:"操作失败",
  failToCall:"调用失败",
  onlyOneType:"一次申请中，只能填写同类的申请",
  wrongWfDef:"工作流定义存在错误",
  invalidInterval:"无效的时间段",
  invalidRatio:"请输入正确的分摊比率",
  plsInputPrj:'请选择项目',
  notInBusiTime:"不在差旅的时间段内",
  hasOverlap:"时间段有重叠",
  dateFmt:"YYYY/MM/DD HH:mm",
  start:'开始时间',
  end:'结束时间',
  
  sex:{
    M:"先生",
    F:"女士",
    O:"未知"
  },
    
  home:{
    attendance:"打卡"
  },
  atd:{
    title:"考勤",
    clockExp:"考勤异常",
    leave:"请假",
    ovt:"加班",
    worktime:"工时申报",
    ovOrLv:'请假或加班',
    ratio:'分摊比率',
    prj:'项目',
    
    aplType:{
      OTW:'加班',
      LEAV:'请假',
      BUSI:'工作日在途'
    },
    aplTmType:{ //时段的类型
      //WORK:'正常上下班',
      WOW:'延长工时',
      OOW:'休息日加班',
      FOW:'节假日加班',
      BUSI:'工作日在途',
      AFFA:'事假',
      SICK:'病假',
      WEAL:'福利假',
      HOLI:'年休假'
    },
    aplSta:{
      INIT:"初始",
      WAIT:'待确认',
      OK:'通过',
      REJ:'拒绝'
    }
  },

  hr:{
    cfmed:'已确认',
    notCfm:'未确认',
    salType:{
      SUBSIDY:'补贴',
      EXPENSE:'报销',
      BONUS:'奖金',
      SHARE:'分红',
      TAX:'税额',
      OVERTIME:'加班工资'
    },
    eventType:{
      JOIN:'入职',
      LEAV:'离职',
      DIS:'开除',
      ADDS:'加薪',
      SUBS:'减薪',
      ASTO:'加股票',
      SSTO:'减股票',
      PROM:'升职',
      DEMO:'降职',
      UPG:'升级',
      DWG:'降级',
      FINE:'罚款',
      WARN:'警告',
      ERR:'记过',
      LAUD:'表扬',
      PRJ:'项目经历',
      OTH:'其他'
    }
  },
  busi:{
    title:'差旅',
    prj:'所属项目',
    reason:'事由',
    dest:'目的地',
    subsidy:'补助',
    expense:'报销',
    invoice:'发票号',
    overAt:'完成时间',
    val:'金额(元)',
    status:'审批状态',
    states:{
      INIT:'初始',
      WAIT:'等待审核',
      REJ:'被拒绝',
      RUN:'进行中',
      OVER:'结束'
    },
    cfmRmv:'确定删除该出差申请吗',
    wfSegs:[
      {t:'s',n:'prjName',s:'项目'},
      {t:'s',n:'account',s:'申请人帐号'},
      {t:'s',n:'dest',s:'目的地'},
      {t:'s',n:'reason',s:'出差事由'},
      {t:'n',n:'expense',s:'报销金额'},
      {t:'n',n:'subsidy',s:'补助'},
      {t:'dt',n:'start',s:'开始时间'}, 
      {t:'dt',n:'end',s:'结束时间'},
      {t:'s',n:'cmt',s:'说明'}
    ]
  },
  my:{
    title:"我的",
    event:"关键事件",
    perm:"绩效",
    res:"资产",
    salary:"工资",
    grp:"部门"
  },
  
  prj:{
    title:'项目',
    member:'成员',
    plan:"计划",
    target:"目标",
    subPrj:'子项目',
    stage:"阶段",
    base:'达标值',
    challenge:'挑战值',
    real:'实际值',
    account:"帐号",
    mbrRole:'角色',
    
    type:"类型",
    start:"开始时间",
    end:"结束时间",
    realEnd:"实际结束时间",
    owner:"投资人",
    leader:"项目经理",
    scope:"范围",
    finish:"完成",
    appraise:"评价",
    cancel:"取消",
    
    typeCfg:{
      PROD:'生产',
      RND:'研发',
      HR:'人力资源',
      PUR:'采购',
      TRAI:'培训',
      SALE:'销售',
      OTH:'其他'
    },
    
    roleCfg:{
      L:"项目经理",
      O:"投资人",
      W:"普通成员"
    },
    
    stageCfg:{
      INIT:'初始',
      START:'启动',
      RUN:'进行中',
      END:'完成',
      CANC:'取消'
    },
    planSta:{
      INIT:'未完成',
      NORM:'正常完成',
      ADVA:'提前完成',
      DELA:'延迟完成',
      CANC:'取消'
    },
    targetSta:{
      INIT:'未完成',
      DONE:'完成'
    }
  },
  grp:{
    title:'群组',
    department:'部门',
    member:'成员',
    contacts:'通讯录',
    atd:'加班请假申请',
    role:{
        ADM:"经理",
        HR:"人事",
        SEC:"秘书",
        NOR:"员工", //NOR的工资才会由部门负担
        OTH:"其他"
    },
    type:{D:"部门",V:"群组"},
    struct:"组织结构",
    clockExp:"考勤异常确认",
    perf:"绩效管理",
    perfCmt:"绩效说明",
    mbrTitle:"职位",
    mbrRole:"角色",
    account:"帐号"
  },

  sta2icon:function(s){
    if(s==0) {
      return 'star_border';
    }
    if(s==100) {
      return 'star';
    }
    return 'star_half';
  },
  
  errMsgs:{
    4100:'工时未完全申报',
    4101:'已确认的工时不可更改',
    6001:"无效的开始结束时间段",
    6002:"必须按整小时请假",
    6003:"年休假，必须按天请请假",
    6004:"年休假余额不足",
    6005:"福利假必须按小时请",
    6006:"福利假余额不足",
    6007:"非工作时段，无需请假",
    6008:"工作时段，不可加班",
    6009:"非工作时段，无需申请在途免打卡",
    6010:"存在重复的申请",
    6011:'请假时段，不可刷卡',
    6012:'请假时段已刷卡',
    6013:'加班时段无刷卡记录',
    
    6101:"存在未完成的计划，不可结束项目",
    6103:"超过最大忘刷卡次数",
    6107:'无有效的工时记录'
  }
}
};