export default {
en:{
  app_name:"Settings",
  ok:"OK",
  cancel:"Cancel",
  close:"Close",
  advanced:"Advanced",
  addCompany:"Add Company",
  save:"Save",
  login:"Login",
  logout:"Logout",
  invalidEmail:"Please input a valid email",
  invalidMobile:"Please input a valid phone number",
  invalidExtIP:"Please input a valid outside IP address",
  insideAddr:"LAN IP",
  outsideAddr:"WAN IP",
  mobile:"Mobile",
  service:"Service",
  send:"Send",
  email:"Email",
  account:"Account",
  chgPwd:"Change password",
  cantbeNull:"Can't be null",
  mustbeEqual:"Must be the same",
  pwd:"Password",
  oldPwd:"Old Password",
  newPwd:"New Password",
  cfmPwd:"Confirm Password",
  verifyCode:"Verify Code",
  invalidPwd:"'New Password' can't be null, and must be the same as 'Confirm Password'",
  nickName:"Nick Name",
  failToCall:"Fail to call",
  successToCall:"Succeed to call",
  alert:"Alert",
  successToConnect:"Succeed to connect server",
  register:"Register",
  checkin:"Check In",
  notStart:"Haven't stated",
  copied:"Copied",
  adviceFmt:"Service Name：xxxxx\nAdvice type：New requirement/For improvement\nContent：xxxxxxx",
  sendAdvice:"Send advices to Email or QQ of ZhijianMesh",
  openSrcs:"Share views in github, gitee or gitcode",
  fmtLike:"Format",

  errMsgs:{
    'unknown':"Unknown",
    '5101':"Please input 'Company ID' and try again",
    '5102':"No proper server"
  },
  home:{
    personal:"Account",
    company:"Company",
    advice:"Feedback",
    register:"Register",
    exitCompany:"Exit Current Company",
    about:"Abount"
  },
  cfg:{
    title:"Company Settings",
    id:"Company ID",
    name:"Company Name",
    pwd:"Password",
    auth:"Authorize",
    address:"Address",
    creditCode:"Company Credit Code",
    accessCode:"Access Code",
    tokenPwd:'Token Password',
    logo:"Logo",
    backupAt:"Backup At",
    logLevel:"Log Level",
    backup:"Database Backup",
    nwSettings:"Network Settings",
    outsideTest:"Outside Network Test",
    outTestDesc:"Used to test whether an IP can be accessed from outside network",
    baseSettings:"Basic Settings",
    remoteTest:"Remote Test",
    title:"Company Settings",
    state:"State",
    invalidPwd:"Password must contains 6 characters at least, and at least 2 types of characters(letters/numbers/others). Can't contain many duplicate characters.",
    invalidCfmPwd:"Confirm-password must be the same as Password",
    invalidCredit:"Invalid company credit code",
    sucessToReg:"Succeed to register, company ID:"
  }
},
zh:{
  app_name:"设置",
  ok:"确定",
  cancel:"取消",
  close:"关闭",
  advanced:"高级",
  addCompany:"增加公司",
  save:"保存",
  login:"登录",
  logout:"退出",
  invalidEmail:"请输入正确的邮箱",
  invalidMobile:"请输入正确的手机号",
  invalidExtIP:"不是正确的公网地址",
  insideAddr:"内网地址",
  outsideAddr:"外网地址",
  mobile:"手机号",
  service:"服务",
  send:"发送",
  email:"邮箱",
  account:"帐号",
  chgPwd:"修改密码",
  cantbeNull:"不能为空",
  mustbeEqual:"必须相同",
  oldPwd:"原密码",
  newPwd:"新密码",
  cfmPwd:"确认密码",
  invalidCfmPwd:"确认密码必须与密码相同",
  successToChgPwd:"密码已修改",

  verifyCode:"验证码",
  invalidPwd:"密码不符合要求，请更正后再尝试",
  nickName:"昵称",
  failToCall:"调用失败",
  successToCall:"调用成功",
  alert:"提示",
  successToConnect:"已成功连接服务器",
  register:"注册",
  checkin:"接入",
  notStart:"未启动",
  copied:"已复制到剪贴板",
  adviceFmt:"服务名称：xxxxx\n建议类型：新需求/改进建议\n内容：xxxxxxx",
  sendAdvice:"将建议发送到至简网格的邮箱或QQ",
  openSrcs:"也可以在开源库中与我们交流",
  fmtLike:"格式如下",

  errMsgs:{
    'unknown':"未知错误",
    '5101':"请在‘公司信息’中设置公司编号之后再尝试",
    '5102':"没有合适的服务器可以使用"
  },
  user:{
    createAt:"创建时间",
    birthday:"生日",
    sex:"性别",
    sexOpts:[{label:"男",value:"M"},{label:"女",value:"F"}]
  },
  home:{
    personal:"帐号信息",
    company:"公司信息",
    advice:"意见反馈",
    register:"注册",
    exitCompany:"退出当前公司",
    about:"关于"
  },
  cfg:{
    title:"公司设置",
    id:"公司ID",
    name:"公司名称",
    pwd:"密码",
    auth:"鉴权",
    address:"地址",
    creditCode:"统一信用码",
    accessCode:"接入码",
    tokenPwd:'临时令牌密码',
    logo:"公司图标",
    backupAt:"每日备份时间点",
    logLevel:"日志级别",
    backup:"数据备份",
    nwSettings:"网络接入",
    outsideTest:"外网测试",
    outTestDesc:"用于测试所选地址是否可以从外网访问",
    baseSettings:"基本设置",
    remoteTest:"调测设置",
    title:"公司设置",
    state:"状态",
    invalidPwd:"密码必须大于6个字符，至少需要二种不同的字符（字母、数字、其他），且不可有太多重复字符",
    invalidCfmPwd:"密码必须与确认密码一致",
    invalidCredit:"无效的统一信用码",
    sucessToReg:"注册成功，公司ID为："
  }
}
};
