export default {
en:{
  app_name:"HR",
  ok:"OK",
  cancel:"Cancel",
  modify:"Modify",
  remove:"Delete",
  add:"Add",
  save:"Save",
  search:"Search"
},
zh:{
  app_name:"人力资源",
  ok:"确定",
  cancel:"取消",
  close:"关闭",
  modify:"修改",
  remove:"删除",
  add:"增加",
  save:"保存",
  search:"搜索",
  age:"岁",
  cmt:"备注",
  start:"开始",
  end:"结束",
  name:"名称",
  initCal:"初始化",
  wrongWfDef:"工作流定义存在错误",
  wrongFlowState:"工作流状态错乱，请确认是否清除？",
  
  sex:{
    M:"先生",
    F:"女士",
    O:"未知"
  },
  yesNo:{
    Y:'是',
    N:'否'
  },
  aplSta:{ //申请状态
    INIT:"初始",
    WAIT:'待确认',
    OK:'通过',
    REJ:'拒绝'
  },
  edu:{
    E0:"无",
    E1:"小学",
    E2:"初中",
    E3:"高中-中专",
    E4:"大专",
    E5:"本科",
    E6:"研究生",
    E7:"博士生",
    E8:"博士后"
  },
  salTp:{
    SALARY:'工资',
    SUBSIDY:'补贴',
    EXPENSE:'报销',
    BONUS:'奖金',
    SHARE:'分红',
    TAX:'个人所得税',
    SECURITY0:'劳动保障(个人)',
    SECURITY1:'劳动保障(公司)',
    OLD:'养老保险',
    MEDICARE:'医疗保险',
    JOB:'失业保险',
    INJURY:'工伤保险',
    PCREATION:'生育保险',
    HOUSE:'住房公积金'
  },
  sponTp:{
    P:"个人交",
    C:"公司交"
  },
  evtType:{
    JOIN:"入职",
    LEAV:"离职",
    ADDS:"加薪",
    SUBS:"减薪",
    ASTO:'加股票',
    SSTO:'减股票',
    DEMO:"降职",
    PROM:"升职",
    UPG:"升级",
    DWG:"降级",
    FINE:"罚款",
    WARN:"警告",
    ERR:"记过",
    DIS:"开除",
    PRJ:"项目经历",
    LAUD:"表扬",
    OTH:"其他"
  },
  perState:{
    INIT:'初始',
    CONT:'接触',
    EXAM:'面试',
    REJ:'被拒绝',
    DISC:'公司放弃',
    PROC:'正在入职',
    JOIN:'已入职',
    LEAV:"已离职",
    DIS:'被开除'
  },
  empState:{
    NORM:"正常",
    HIDE:"隐藏",
    DIS:"被开除",
    LEAV:"已离职"
  },
  attendTp:{
    NORM:"打卡机刷卡",
    LAN:"内网打卡",
    REMO:"远程",
    FREE:"不打卡"
  },
  resumeTp:{
    EDU:'学校教育',
    TRA:'培训',
    PRO:'工作',
    OTH:'其他'
  },
  roleTp:{
    ADM:"负责人",
    HR:"HR",
    SEC:"秘书",
    NOR:"成员"
  },
  securityTp:{
    OLD:'养老保险',
    MEDICARE:'医疗保险',
    JOB:'失业保险',
    INJURY:'工伤保险',
    PCREATION:'生育保险',
    HOUSE:'住房公积金'
  },
  securityProp:{
    P:'个人缴纳',
    C:'公司缴纳',
    R:'按比率',
    V:'固定金额'
  },
  pub:{
    account:"帐号",
    name:"姓名",
    sex:"性别",
    contact:"联系方式",
    ability:"能力",
    phone:"联系电话",
    email:"邮箱",
    birth:"生日"
  },
  pool:{
    title:"人才库",
    detail:"人才",
    expSalary:"期望的工资",
    cmt:"备注",
    entry:"入职",
    state:'状态',
    contact:"联系记录",
    at:"时间"
  },
  employee:{
    title:"员工列表",
    detail:"员工",
    name:"姓名",
    quali:"任职资格",
    post:"任职等级",
    worktime:"作息",
    entryAt:"入职日期",
    email:"工作邮箱",
    addr:"住址",
    name:"姓名",
    salary:"基本工资(元)",
    dSalary:"日薪(元)",
    hSalary:"时薪(元)",
    subsidy:"出差补贴(元)",
    idno:"身份证号",
    stock:"拥有股份",
    zone:"区域",
    office:"办公区",
    worktime:"作息",
    attend:"考勤方式",
    holiday:"年休假(天)",
    weal:"福利假(小时)",
    sickRatio:"病假工资比率",
    deduction:"税收专项扣除(元)",
    state:"状态",
    event:"关键事件",
    leave:"离职",
    join:"入职",
    resume:"简历",
    manage:'人事审批',
    maxEdu:"最高学历",
    firstEdu:"第一学历",
    account:'帐号',
    signer:'权签人',
    setGrade:'任职',
    setSalary:'调薪',
    setStock:'调股'
  },
  resume:{
    org:"机构",
    contrib:"贡献与收获",
    type:"性质"
  },
  grp:{
    title:"组织管理",
    role:"角色",
    create:"新建",
    name:"名称",
    descr:"描述",
    type:"类型",
    addMbr:"添加成员",
    mbrTitle:"职位",
    account:"帐号"
  },
  cfg:{
    title:"HR配置",
    
    zone:"大区",
    office:"办公区",
    worktime:"作息制度",
    calendar:"日历",
    perf:"绩效等级",
    workDay:"工作日",
    festival:"节假日",
    offDay:"休息日",
    midClock:'午休需打卡',
    
    subsidy:'补贴系数',
    salary:'工资系数',
    fowSalary:'节假日加班工资系数',
    oowSalary:'休息日加班工资系数',
    wowSalary:'工作日加班工资系数',
    timeOff:'时区偏差(分钟)',
    taxFunc:'计税函数',
    
    security:"社会保障",
    val:"金额或比率",
    
    calendar:'工作日历',
    first:'上班时间(分钟)',
    second:'上午下班时间(分钟)',
    third:'下午上班时间(分钟)',
    forth:'下班时间(分钟)',
    leadTime:'刷卡提前量(分钟)',
    maxEdit:'每月最大忘刷卡次数',
    
    level:'等级',
    month:'月'
  },
  grpTp:{
    D:"部门",
    V:"群组"
  },
  salary:{
    title:"发薪"
  },
  flowTags:{
  },
  weekDays:['日','一','二','三','四','五','六'],
  errMsgs:{
    '6004':'年休假必须请整天',
    '6005':'福利假不能打散请',
    '6006':'没有足够的年休假',
    '6007':'没有足够的福利假',
    '6008':'没有足够的休假指标',
    '6009':'离职前必须清理资产',
    '6104':'不可能在工作日整天加班',
    '6105':'不能在工作时段加班',
    '6106':'请假时段必须为整小时',
    '6107':'未填工时，或工时未确认',
    '6108':'待删除组织或部门不为空',
    '6109':'群组下不能添加部门',
    '6110':'区域被引用',
    '6111':'日历被引用',
    '6200':'超过考勤修改次数上限',
    '6201':'存在员工数据引用',
    '6202':'雇员信息不可删除',
    '6203':'被对方拒绝或公司放弃的人才才可以删除',
    '6204':'已经入职或不在人才库中',
    'unknown':'未知错误'
  }
}
};