export default {
en:{
  app_name:"SystemOM",
  ok:"OK",
  cancel:"Cancel",
  close:"Close",
  remove:'Delete',
  noToken:"Never checked in, can't use it",
  neverBackup:"No backups",
  service:"Service",
  chgPwd:"Change password",
  oldPwd:"Old Password",
  newPwd:"New Password",
  cfmPwd:"Confirm Password",
  failToCall:"Fail to call",
  alert:"Alert",
  running:"Running",
  startup:"Startup",
  shutdown:"Shutdown",
  dontSet:"Don't set",
  baseSettings:"Basic settings",

  backupSuccess:"Database backup succeeded",
  backupAlert:"<div>Each backup will decrease one backup chance!</div><p>Continue or not?</p>",
  restoreSuccess:"Succeeded to restore data, please restart server to valid id.",
  restoreAlert:"<div>Server will shutdown before restoring data. Local data will be covered. All the data from previous backup-point will be lost.</div><p>Continue or not?</p>",
  needBuckets:"Must select at least one backup-site",
  succeedToConnect:"Succeeded to access from outside network",
  failToConnect:"Can't access from outside network",
  invalidCfmPwd:"Confirm-password must be the same as Password",
  errMsgs:{
    'unknown':"Unknown",
    '5101':"Please input 'Company ID' and try again",
    '5102':"No proper server"
  },
  cfg:{
    title:"Company Settings",
    id:"Company ID",
    name:"Company Name",
    pwd:"Password",
    auth:"Authorize",
    address:"Address",
    creditCode:"Company Credit Code",
    accessCode:"Access Code",
    tokenPwd:'Token Password',
    logo:"Logo",
    backupAt:"Backup At",
    logLevel:"Log Level",
    backup:"Database Backup",
    nwSettings:"Network Settings",
    outsideTest:"Outside Network Test",
    outTestDesc:"Used to test whether an IP can be accessed from outside network",
    baseSettings:"Basic Settings",
    remoteTest:"Remote Test",
    title:"Company Settings",
    pubGwIp:"Gateway IP",
    recentBackup:"Latest Backup At",
    buckets:"Backup Sites",
    restore:"Restore",
    backupNow:"Backup Now",
    invalidCid:"Invalid company ID",
  },
  om:{//管理台
    title:"Advanced maintenance tools",
    execsqls:"Execute sqls",
    serverlogs:"Server logs",
    srvNodes:"Service nodes",
    dbNodes:"Database nodes",
    service:"Service",
    serviceMng:'Service Management',
    db:"Database",
    useTime:"Use Time:",
    dlList:"Download List",

    partId:"Partition",
    dbNo:"Database NO",
    addr:"Address",
    status:"Status",
    ver:"Version",
    level:"Level",
    slaves:"Slaves",
    sharding:"Sharding",
    shardStart:"Sharding Start",
    shardEnd:"Sharding End",
    cfmRmvSrv:'Are you sure to remove webdb server?',
    cfmRmvDbNode:'Are you sure to remove webdb node?',
    advRmvService:'Not exists,want you clear it?'
  },
  mkt:{
    title:"Service manage",
    services:"Market",
    locServices:"Intalled services",
    search:"Search",
    updateAt:"Update at",
    author:"Author",
    version:"Version",
    waitting:"Executing...",
    update:"Update",
    unInstall:"Uninstall",
    install:"Install",
    cfmUpdate:"Confirm updating",
    cfmInstall:"Confirm installing",
    cfmUninstall:"Confirm uninstalling",
    successToInstall:"Succeed to install",
    successToUnInstall:"Succeed to uninstall"
  },
  service:{
    name:"Name",
    db:"Database",
    caller:'Caller',
    keypair:"Key Pair",
    configs:'Configures',

    install:"Install serivce",
    requests:"Request stats",

    initTitle:"Initialize database",
    initSuccess:"Success to initialize database",
    initAlert:"Re-initialize database.If there are wrong sql,it will fail and may lose data!",
    fails:"Fails",
    excs:"Exceptions",
    unit:"Times"
  }
},
zh:{
  app_name:"系统维护",
  ok:"确定",
  cancel:"取消",
  close:"关闭",
  remove:'删除',
  noToken:"登录失效，无法使用",
  neverBackup:"尚无备份",
  service:"服务",
  chgPwd:"修改密码",
  oldPwd:"原密码",
  newPwd:"新密码",
  cfmPwd:"确认密码",
  invalidCfmPwd:"确认密码必须与密码相同",
  successToChgPwd:"密码已修改",

  failToCall:"调用失败",
  alert:"提示",
  running:"运行中",
  startup:"启用",
  shutdown:"停用",
  dontSet:"不设置",
  doing:"任务执行中",
  baseSettings:"基本设置",

  backupSuccess:"数据已成功备份。",
  backupAlert:"<div>每次数据备份将占用一次备份机会。</div><p>请确认是否继续？</p>",
  restoreSuccess:"已成功恢复数据，请重新启动服务使数据生效。",
  restoreAlert:"<div>恢复数据会首先停止服务器，并使用备份数据覆盖本地数据库，自上个备份时间点到当前时间产生的数据会丢失。</div><p>请确认是否继续？</p>",
  needBuckets:"至少需要选择一个备份点",
  succeedToConnect:"可以从外网访问",
  failToConnect:"不可以从外网访问",
  errMsgs:{
    'unknown':"未知错误",
    '5101':"请在‘公司信息’中设置公司编号之后再尝试",
    '5102':"没有合适的服务器可以使用"
  },
  cfg:{
    title:"公司设置",
    id:"公司ID",
    name:"公司名称",
    pwd:"密码",
    auth:"公司密码认证",
    address:"地址",
    creditCode:"统一信用码",
    accessCode:"接入码",
    tokenPwd:'临时令牌密码',
    logo:"公司图标",
    backupAt:"每日备份时间点",
    logLevel:"日志级别",
    backup:"数据备份",
    nwSettings:"网络接入",
    outsideTest:"外网测试",
    outTestDesc:"用于测试所选地址是否可以从外网访问",
    baseSettings:"基本设置",
    remoteTest:"调测设置",
    title:"公司设置",
    pubGwIp:"公网地址",
    recentBackup:"最近备份时间",
    buckets:"备份站点",
    restore:"恢复数据",
    backupNow:"立即备份",
    invalidCid:"公司ID不正确"
  },
  om:{//管理台
    title:"高级维护工具",
    execsqls:"数据库操作",
    serverlogs:"服务侧日志",
    srvNodes:"服务实例",
    dbNodes:"数据库实例",
    service:"服务",
    serviceMng:'服务管理',
    db:"数据库",
    useTime:"耗时:",
    dlList:"下载列表",

    partId:"分区号",
    dbNo:"编号",
    addr:"IP地址",
    status:"状态",
    ver:"版本号",
    level:"等级",
    slaves:"从节点",
    sharding:"分片",
    shardStart:"分片开始",
    shardEnd:"分片结束",
    cfmRmvSrv:'确定删除webdb服务实例吗？',
    cfmRmvDbNode:'确定删除数据库节点吗？',
    advRmvService:'数据缺失，是否删除它？'
  },
  mkt:{
    title:"应用管理",
    services:"应用市场",
    locServices:"已安装应用",
    search:"搜索",
    updateAt:"更新于",
    author:"作者",
    version:"版本",
    waitting:"执行中...",
    update:"更新",
    unInstall:"卸载",
    install:"安装",
    cfmUpdate:"更新服务",
    cfmInstall:"安装服务",
    cfmUninstall:"卸载服务",
    successToInstall:"安装成功",
    successToUnInstall:"卸载成功"
  },
  service:{
    name:"服务",
    db:"数据库",
    caller:'调用方',
    keypair:"密钥对",
    configs:'配置项',
    
    install:"安装服务",
    requests:"访问统计",

    initTitle:"数据库初始化",
    initSuccess:"数据库初始化成功",
    initAlert:"重新初始化数据库，如果初始化脚本设计有问题，会导致数据丢失！",
    fails:"失败统计",
    excs:"异常",
    unit:"次"
  }
}
};
