export default {
en:{
  app_name:"Extream CRM",
  ok:"OK",
  cancel:"Cancel",
  modify:"Modify",
  remove:"Delete",
  add:"Add"
},
zh:{
  app_name:"极简CRM",
  ok:"确定",
  cancel:"取消",
  close:"关闭",
  modify:"修改",
  remove:"删除",
  add:"增加",
  search:"搜索",
  cmt:"备注",
  start:'开始时间',
  end:'结束时间',
  wrongFlowState:"工作流状态错乱，请确认是否清除？",
  
  dateFmt:"YYYY/MM/DD HH:mm",
  
  touchCtnt:"沟通内容",
  relationCmt:"关系描述",
  addCust:"创建客户",
  addContact:"增加联系人",
  address:"地址",
  taxid:"统一信用码",
  business:"主营业务",
  signers:"权签人",
  contactLevel:"重要度",
  sex:"性别",
  yearsOld:"岁",
  sexName:{M:'男',F:'女',U:'未知'},
  sexImg:{
    M:'svguse:/assets/imgs/meshicons.svg#man',
    F:'svguse:/assets/imgs/meshicons.svg#woman'
  },
  unknown:"未知",
  
  taxidPls:"统一信用码需由18位字母、数组的组合而成",

  alert:"注意",
  failToCall:"调用失败",
  cfmToDel:"请确认是否删除",

  touchlog:"联系记录",
  contactRelations:"联系人之间关系",
  relations:"周边关系",
  
  unit:{y:"元",g:"个"},

  baseInfo:"基本信息",
  mobile:"手机",

  mobilePls:"请输入11位正确的手机号！",
  exceedsDayNum:"报表周期不可超过31天！",
  invalidRange:"报表周期至少1个月，最多12个月",
  onlyMine:"只看我的",
  forever:"永久",
  notOver:'未完成',

  levels:['普通','一般','重要','很重要','关键人物'],
  errMsgs:{
    '5101':"回款总额超过合同总额",
    '5102':"订单尚未确认，不可创建回款",
    '5103':"处于审批流程中的订单不可更改",
    '5104':"已结束的服务信息不可更改",
    '5105':"已结束的回款信息不可更改",
    '5106':"输入的帐号不符合要求",
    '5107':"商品已被使用，不可删除",
    '5108':"下一步会签，责任人不可以有自己",
    '5109':"下一步只可指定一个责任人",
    '5110':"必须指定下一步责任人",
    '5111':'正在进行中的工作流，不可以删除',
    '5112':'采购SKU不在订单列表中',
    '5113':'采购量超过订单量',
    '5114':'订单中必须指定SKU',
    'unknown':"未知错误"
  },
  home:{
    customers:"客户",
    contacts:"联系人",
    orders:"订单",
    payments:"回款",
    services:"服务单",
    template:"模板设置",
    bulletin:"简报",
    balance:"结算"
  },
  customer:{
    title:"客户",
    name:"名称",
    ordNum:"订单数",
    address:"地址",
    createAt:"创建时间",
    creator:"创建人",
    taxid:"统一信用码",
    status:"审批状态",
    business:"主营业务",
    lastestTl:"最近联系记录"
  },
  contact:{
    title:"联系人",
    cname:"客户",
    name:"称呼",
    address:"住址",
    createAt:"创建时间",
    creator:"创建人",
    status:"状态",
    level:"重要度",
    phone:'电话',
    sex:"性别",
    post:"职位",
    birthday:"出生年月"
  },
  order:{
    title:"订单",
    code:"订单号",
    status:"审批状态",
    cname:"客户",
    price:"合同价",
    payment:"回款总额",
    needPay:"待回款",
    skuName:"商品",
    skuPrice:"目录价",
    skuNum:'数量',
    skuList:'销售清单',
    creator:"创建人",
    createAt:"创建时间",
    signAt:"确定时间",
    fileNo:"合同文本",
    taxid:"统一信用码",
    prj:'所属项目'
  },
  payment:{
    title:"回款",
    amount:"回款金额",
    status:"审批状态",
    cname:"客户",
    bank:'银行帐号',
    creator:"创建人",
    createAt:"创建时间",
    cfmAt:'确认于',
    notCfm:'未确认'
  },
  cost:{
    title:"成本",
    val:"金额(元)",
    type:'类型',
    cname:"客户",
    creator:"创建人",
    createAt:"创建时间",
    types:{
      GOOD:'货物成本',
      BUSI:'差旅',
      GIFT:'礼品',
      SERV:'服务',
      OTH:'其他'
    }
  },
  busi:{
    title:'差旅',
    dest:'目的地',
    reason:'事由',
    account:'出差人员'
  },
  report:{
    customer:"客户",
    contact:"联系人",
    ord:"订单",
    service:"服务",
    payment:"回款数",
    contract:"合同额",
    revenue:"回款额",
    cost:"成本",
    main:"简报",
    sku:"商品结算",
    month:"月度收支"
  },
  menu:{
    deliver:"转交",
    remove:"删除",
    deliverTo:"转交给",
    export:"导出"
  },
  share:{
    title:"数据分享",
    to:"分享给",
    endT:"结束日期",
    O:"全权",
    S:"只读"
  },
  purchase:{
    title:'采购申请',
    buyer:'采购负责人',
    receiver:'收件人',
    expDate:'期望到货日期',
    skuList:'采购清单'
  },
  icons:{//各功能的图标
   customer:"svguse:/assets/imgs/meshicons.svg#company",
   contact:"contacts",
   order:"event_note",
   service:"svguse:/assets/imgs/meshicons.svg#build",
   payment:"svguse:/assets/imgs/meshicons.svg#payment",
   touchlog:"perm_phone_msg"
  },
  flowTags:{}
}
}