export default {
en:{
app_name:"groups management",
failToCall:"Failed",
close:"Close",
ok:"OK",
account:"Account",
role:"Role",
pwd:"Password",
createAt:"Create at",
name:"Name",
descr:"Description",
addMbr:"Add employee",
crtGrp:"Create group",
owner:"Owner"
},
cn:{
app_name:"帐号管理",
grps:"组织管理",
authorize:"服务授权",
failToCall:"调用失败",
close:"关闭",
remove:"删除",
ok:"确定",
createAt:"创建时间",
addMbr:"增加成员",
setPower:"员工授权",
crtGrp:"创建组织",
editGrp:"修改组织",
owner:"管理员",
newUser:"新增用户",
mobilePls:"请输入11位正确的手机号！",
emailPls:"请输入正确的邮箱地址！",
save:"保存",

user:{
    status:"激活/禁用", 
    account:"帐号",
    email:"邮箱",
    role:"角色",
    power:"服务权限",
    pwd:"密码",
    pwdReseted:"密码已重置，请记住以下密码（区分大小写）:",
    resetPwd:"重置密码",
    groups:"任职部门",
    nickName:"昵称",
    mobile:"电话",
    loginAt:"登录时间",
    createAt:"创建时间",
    birthday:"生日",
    sex:"性别",
	sexTitles:{"M":"男","F":"女"},
	sexOpts:[{label:"男",value:"M"},{label:"女",value:"F"}]
},
grp:{
    name:"部门名称",
    descr:"描述",
    title:"职位",
    fname:'上层组织'
},
power:{
    service:"服务名",
    role:"角色",
    pubAccess:"公网访问",
    ext:"扩展权限"
},
errMsgs:{
  'unknown':"未知错误",
}
}
}