export default {
en:{
  app_name:"Operate&Manage",
  ok:"OK",
  cancel:"Cancel",
  add:"Add"
},
zh:{
  app_name:"快易记账",
  ok:"确定",
  cancel:"取消",
  close:"关闭",
  add:"增加",
  save:"保存",
  confirm:"确认",
  search:"搜索",
  remove:'删除',
  more:"更多",
  onlyMine:"只看我的",
  start:'开始',
  stop:'结束',
  
  noRights:"无权限，请连续管理员申请权限",
  settings:"系统设置",
  birth:"生日",
  
  order:{
    title:'订单',
    val:"订单金额",
    state:'订单状态',
    bankAcc:'付款帐号',
    refund:'退款金额'
  },
  vip:{
    name:'会员',
    total:'充值总额',
    balance:'余额',
    code:"编码"
  },
  service:{
    title:"服务",
    myTask:"我的任务",
    val:'服务金额',
    state:'服务状态',
    start:"开始时间",
    end:"完成时间",
    notStart:'未开始',
    notEnd:'未完成',
    useTime:'用时',
    unit:'分钟',
    busy:'服务中，不能接单',
    cmt:'评价',
    noCmt:'尚无评价'
  },
  brokerage:{
    title:'提成',
    owner:'员工帐号',
    ratio:'提成比率(%)',
    val:'金额',
    types:{
      ORD:'订单',
      SRV:'服务'
    }
  },
  
  unit:{T:"个",Y:"元"},
  sexInfo:{
    F:{i:"girl",n:"女"},
    M:{i:"boy",n:"男"},
    U:{i:"no_accounts",n:"未知"}
  },
  cfgTags:{
      changeNotSaved:"修改的内容尚未保存，请确认是否放弃修改？",
      needAz:'字段必须是a-z、A-Z字符的组合',
      segTypes:{'s':'文字','n':"数值",'d':'日期'},
      asMap:'模板格式',
      segKey:'字段',
      segName:"名称",
      segType:"类型",
      val:'配置内容'
  },
  name:"称呼",
  
  sex:"性别",
  mobile:"手机",
  email:'邮箱',
  createAt:"创建时间",
  age:"岁",
  creator:"创建人",
  createAt:"创建时间",
  cfmOrder:"确认订单",
  cfmService:"确认服务单",
  addVip:"增加会员",
  addOrder:"创建订单",
  addService:"增加服务单",
  serviceVal:"消费额",
  supplier:'服务人员',
  cmt:"备注",
  mobilePls:"请输入11位手机号",
  namePls:"请输入正确的称呼",
  cfmOrderAlert:'订单确认后无法更改，请确定是否确认此订单？',
  rmvOrderAlert:'订单删除后无法恢复，请确定是否删除此订单？',
  cfmServiceAlert:'服务单确认后无法更改，请确定是否确认此服务单？',
  rmvServiceAlert:'服务单删除后无法恢复，请确定是否删除此服务单？',

  score:{
    total:'总数',
    vTotal:'总金额',
    vip:'30日新增会员数',
    nOrder:'30日新增订单数',
    vOrder:'30日新增订单金额',
    nService:'30日新增服务数',
    vService:'30日新增服务金额',
    vBrokerage:'30日新增提成'
  },

  report:{
    title:'报表',
    vip:'会员数',
    nOrder:'订单数',
    vOrder:'订单金额',
    nService:'服务数',
    vService:'服务金额',
    vBrokerage:'提成',
    byDay:'按天统计',
    byHour:'按小时统计'
  },
  osState:{
    OK:'已确认',
    WAIT:'待确认',
    ALL:'所有'
  },
  
  errMsgs:{
    '2000':'已经存在',
    '2001':'数据不存在',
    '30001':'余额不足',
    '30002':'订单状态不正确',
    '30003':'服务单状态不正确',
    '30004':'待删除的服务单不存在或状态不正确',
    'unknown':"未知错误"
  }
}
};