export default {
en:{
  ok:"OK",
  cancel:"Cancel",
  app_name:"Server Manager"
},
cn:{
  ok:"确定",
  cancel:"取消",
  close:"关闭",
  app_name:"服务管理",
  home:"服务控制",
  settings:"设置",
  market:"应用市场",
  failToCall:"调用失败",
  cidCantBe0:"公司ID不能为0，请在“设置-公司信息”中设置",
  
  address:"地址",
  creditCode:"统一信用码",
  creditCodePls:"请输入18位正确的统一信用码!",
  companyName:"工商注册名称",
  companyId:"公司ID",
  dnsAccessCode:"接入码",
  pwd:"密码",
  cfmPwd:"确认密码",
  verifyCode:"验证码",
  invalidCfmPwd:"确认密码必须与密码相同",
  updateAt:"更新于",
  author:"作者",
  version:"版本",

  install:"安装",
  unInstall:"卸载",
  update:"更新",
  waitting:"...",
  
  advanced:"高级服务",

  backup:"数据备份",
  wanAccess:"外网接入",
  debug:"调测助手",
  uploadLogs:"上传日志",
  faultreport:"故障上报",
  backupNow:"立即备份",
  restore:"恢复数据",
  accessToken:"访问令牌",
  neverBackup:"尚无备份",
  startup:"启用",
  shutdown:'停用',
  state:"状态",
  backupTime:"最近备份时间",
  backupAt:"每日备份时间点",
  buckets:"备份站点",
  notStart:"未启用",
  running:"已启用",
  wanType:"类型",
  wanTypeOpts:[
    {label:"自有外网IP",value:"1"},
    {label:"网桥代理",value:"2"}
  ],
  gwIp:"公网IP",
  
  locServices:"已安装应用",

  configs:"配置",
  refresh:"刷新",
  logo:"公司图标",

  name:"名称",
  save:"保存",
  register:"注册",
  login:"登录",
  reRegister:"重注册/登录",
  displayName:"中文名",
  author:"作者",
  search:"搜索",
  day:"天",
  hour:"时",
  minute:"分",
  logDownloadable:"日志可下载",
  logLevel:"日志级别",
  failToCall:"调用失败",
  alert:"提示",
  errMsgs:{
    'unknown':"未知错误"
  },
  invalidImg:"请选择有效的图片文件",
  needBuckets:"至少需要选择一个备份点",
  needWanIp:"需要填写一个公网IP",
  backupAlert:"<div>每次数据备份将占用一次备份机会。</div><p>请确认是否继续？</p>",
  backupSuccess:"数据已成功备份。",
  restoreSuccess:"已成功恢复数据，请重新启动服务使数据生效。",
  restoreAlert:"<div>恢复数据会首先停止服务器，并使用备份数据覆盖本地数据库，自上个备份时间点到当前时间产生的数据会丢失。</div><p>请确认是否继续？</p>"
}
};
