export default {
en:{
  app_name:"Settings",
  ok:"OK",
  cancel:"Cancel",
  close:"Close",
  refresh:"Refresh",
  advanced:"Advanced",
  addCompany:"Add Company",
  save:"Save",
  login:"Login",
  logout:"Logout",
  invalidEmail:"Please input a valid email",
  invalidMobile:"Please input a valid phone number",
  invalidExtIP:"Please input a valid outside IP address",
  insideAddr:"LAN IP",
  outsideAddr:"WAN IP",
  inPubCloud:"Access in outer net",
  mobile:"Mobile",
  mobilePls:"Please input 11 mobile number",
  emailPls:"Please input a valid email",
  noToken:"Never checked in, can't use it",
  neverBackup:"No backups",
  advice:'Advice',
  service:"Service",
  send:"Send",
  email:"Email",
  account:"Account",
  chgPwd:"Change password",
  cantbeNull:"Can't be null",
  mustbeEqual:"Must be the same",
  selfSet:"Self defined",
  pwd:"Password",
  oldPwd:"Old Password",
  newPwd:"New Password",
  cfmPwd:"Confirm Password",
  verifyCode:"Verify Code",
  invalidPwd:"'New Password' can't be null, and must be the same as 'Confirm Password'",
  nickName:"Nick Name",
  failToCall:"Fail to call",
  successToCall:"Succeed to call",
  alert:"Alert",
  successToConnect:"Succeed to connect server",
  utCompany:"Company Account",
  utPersonal:"Person Account",
  register:"Register",
  checkin:"Check In",
  running:"Running",
  notStart:"Haven't stated",
  startup:"Startup",
  shutdown:"Shutdown",
  dontSet:"Don't set",
  doing:"Doing",
  copied:"Copied",
  adviceFmt:"Service Name：xxxxx\nAdvice type：New requirement/For improvement\nContent：xxxxxxx",
  sendAdvice:"Send advices to Email or QQ of ZhijianMesh",
  openSrcs:"Share views in github, gitee or gitcode",
  fmtLike:"Format",

  backupSuccess:"Database backup succeeded",
  backupAlert:"<div>Each backup will decrease one backup chance!</div><p>Continue or not?</p>",
  restoreSuccess:"Succeeded to restore data, please restart server to valid id.",
  restoreAlert:"<div>Server will shutdown before restoring data. Local data will be covered. All the data from previous backup-point will be lost.</div><p>Continue or not?</p>",
  needBuckets:"Must select at least one backup-site",
  succeedToConnect:"Succeeded to access from outside network",
  failToConnect:"Can't access from outside network",
  errMsgs:{
    'unknown':"Unknown",
    '5101':"Please input 'Company ID' and try again",
    '5102':"No proper server"
  },
  home:{
    personal:"Account",
    company:"Company",
    advice:"Feedback",
    register:"Register",
    exitCompany:"Exit Current Company",
    about:"Abount"
  },
  cfg:{
    title:"Company Settings",
    id:"Company ID",
    name:"Company Name",
    pwd:"Password",
    auth:"Authorize",
    settings:"Settings",
    address:"Address",
    creditCode:"Company Credit Code",
    accessCode:"Access Code",
    accessToken:'Access Token',
    logo:"Logo",
    backupAt:"Backup At",
    logLevel:"Log Level",
    backup:"Database Backup",
    nwSettings:"Network Settings",
    outsideTest:"Outside Network Test",
    outTestDesc:"Used to test whether an IP can be accessed from outside network",
    baseSettings:"Basic Settings",
    remoteTest:"Remote Test",
    title:"Company Settings",
    state:"State",
    pubGwIp:"Gateway IP",
    setGwIp:"Self-defined GW IP",
    recentBackup:"Latest Backup At",
    buckets:"Backup Sites",
    restore:"Restore",
    backupNow:"Backup Now",
    invalidCid:"Invalid company ID",
    invalidPwd:"Password must contains 6 characters at least, and at least 2 types of characters(letters/numbers/others). Can't contain many duplicate characters.",
    invalidCfmPwd:"Confirm-password must be the same as Password",
    invalidCredit:"Invalid company credit code",
    sucessToReg:"Succeed to register, company ID:"
  },
  om:{//管理台
    title:"Maintenance Tool",
    execsqls:"Execute sqls",
    serverlogs:"Server logs",
    clientlogs:"Client logs",
    serviceState:"Service State",
    savePath:"Logs path",
    service:"Service",
    db:"Database",
    cid:"Company ID",
    sql:"SQL",
    useTime:"Use Time:",
    result:"Result:",
    dlList:"Download List",
    requests:"Request Stat",
    fails:"Failures",
    excs:"Exceptions",
    files:"Files",
    unit:"Times"
  },
  mkt:{
    title:"Service manage",
    services:"Market",
    locServices:"Intalled services",
    search:"Search",
    updateAt:"Update at",
    author:"Author",
    version:"Version",
    displayName:"Display name",
    waitting:"Executing...",
    update:"Update",
    unInstall:"Uninstall",
    install:"Install",
    cfmUpdate:"Confirm updating",
    cfmInstall:"Confirm installing",
    cfmUninstall:"Confirm uninstalling",
	successToInstall:"Succeed to install",
	successToUnInstall:"Succeed to uninstall"
  }
},
cn:{
  app_name:"设置",
  ok:"确定",
  cancel:"取消",
  close:"关闭",
  refresh:"更新",
  advanced:"高级",
  addCompany:"增加公司",
  save:"保存",
  login:"登录",
  logout:"退出",
  invalidEmail:"请输入正确的邮箱",
  invalidMobile:"请输入正确的手机号",
  invalidExtIP:"不是正确的公网地址",
  insideAddr:"内网地址",
  outsideAddr:"外网地址",
  inPubCloud:"外网访问",
  mobile:"手机号",
  mobilePls:"请输入11位手机号码",
  emailPls:"请输入正确的邮箱",
  noToken:"登录失效，无法使用",
  neverBackup:"尚无备份",
  advice:'意见',
  service:"服务",
  send:"发送",
  email:"邮箱",
  account:"帐号",
  chgPwd:"修改密码",
  cantbeNull:"不能为空",
  mustbeEqual:"必须相同",
  selfSet:"自定义",
  pwd:"密码",
  oldPwd:"原密码",
  newPwd:"新密码",
  cfmPwd:"确认密码",
  invalidCfmPwd:"确认密码必须与密码相同",
  successToChgPwd:"密码已修改",

  verifyCode:"验证码",
  invalidPwd:"密码不符合要求，请更正后再尝试",
  nickName:"昵称",
  failToCall:"调用失败",
  successToCall:"调用成功",
  alert:"提示",
  successToConnect:"已成功连接服务器",
  utCompany:"公司帐号",
  utPersonal:"个人帐号",
  register:"注册",
  checkin:"接入",
  running:"运行中",
  notStart:"未启动",
  startup:"启用",
  shutdown:"停用",
  dontSet:"不设置",
  doing:"任务执行中",
  copied:"已复制到剪贴板",
  adviceFmt:"服务名称：xxxxx\n建议类型：新需求/改进建议\n内容：xxxxxxx",
  sendAdvice:"将建议发送到至简网格的邮箱或QQ",
  openSrcs:"也可以在开源库中与我们交流",
  fmtLike:"格式如下",

  backupSuccess:"数据已成功备份。",
  backupAlert:"<div>每次数据备份将占用一次备份机会。</div><p>请确认是否继续？</p>",
  restoreSuccess:"已成功恢复数据，请重新启动服务使数据生效。",
  restoreAlert:"<div>恢复数据会首先停止服务器，并使用备份数据覆盖本地数据库，自上个备份时间点到当前时间产生的数据会丢失。</div><p>请确认是否继续？</p>",
  needBuckets:"至少需要选择一个备份点",
  succeedToConnect:"可以从外网访问",
  failToConnect:"不可以从外网访问",
  errMsgs:{
    'unknown':"未知错误",
    '5101':"请在‘公司信息’中设置公司编号之后再尝试",
    '5102':"没有合适的服务器可以使用"
  },
  user:{
	createAt:"创建时间",
    birthday:"生日",
    sex:"性别",
	sexOpts:[{label:"男",value:"M"},{label:"女",value:"F"}]
  },
  home:{
    personal:"帐号信息",
    company:"公司信息",
    advice:"意见反馈",
    register:"注册",
    exitCompany:"退出当前公司",
    about:"关于"
  },
  cfg:{
    title:"公司设置",
    id:"公司ID",
    name:"公司名称",
    pwd:"密码",
    auth:"鉴权",
    settings:"管理",
    address:"地址",
    creditCode:"统一信用码",
    accessCode:"接入码",
    accessToken:'控制台令牌',
    logo:"公司图标",
    backupAt:"每日备份时间点",
    logLevel:"日志级别",
    backup:"数据备份",
    nwSettings:"网络接入",
    outsideTest:"外网测试",
    outTestDesc:"用于测试所选地址是否可以从外网访问",
    baseSettings:"基本设置",
    remoteTest:"调测设置",
    title:"公司设置",
    state:"状态",
    pubGwIp:"公网地址",
    setGwIp:"自定义地址",
    recentBackup:"最近备份时间",
    buckets:"备份站点",
    restore:"恢复数据",
    backupNow:"立即备份",
    invalidCid:"公司ID不正确",
    invalidPwd:"密码必须大于6个字符，至少需要二种不同的字符（字母、数字、其他），且不可有太多重复字符",
    invalidCfmPwd:"密码必须与确认密码一致",
    invalidCredit:"无效的统一信用码",
    sucessToReg:"注册成功，公司ID为："
  },
  om:{//管理台
    title:"维护工具",
    execsqls:"数据库操作",
    serverlogs:"服务侧日志",
    clientlogs:"端侧日志",
    serviceState:"服务状态",
    savePath:"日志路径",  
    service:"服务",
    db:"数据库",
    cid:"公司ID",
    sql:"SQL",
    useTime:"耗时:",
    result:"结果:",
    dlList:"下载列表",
    requests:"访问统计",
    fails:"失败统计",
    excs:"异常",
    files:"静态文件",
    unit:"次",
	sericeName:"服务",
	cpuTime:"执行时长(ms)",
	queries:"执行次数",
	hasDb:"有数据库",
	noDb:"无数据库"
  },
  mkt:{
    title:"应用管理",
    services:"应用市场",
    locServices:"已安装应用",
    search:"搜索",
    updateAt:"更新于",
    author:"作者",
    version:"版本",
    displayName:"中文名",
    waitting:"执行中...",
    update:"更新",
    unInstall:"卸载",
    install:"安装",
    cfmUpdate:"更新服务",
    cfmInstall:"安装服务",
    cfmUninstall:"卸载服务",
	successToInstall:"安装成功",
	successToUnInstall:"卸载成功"
  }
}
};
