export default {
en:{
  app_name:"HR",
  ok:"OK",
  cancel:"Cancel",
  modify:"Modify",
  remove:"Delete",
  add:"Add",
  save:"Save",
  search:"Search"
},
cn:{
  app_name:"资源管理",
  ok:"确定",
  cancel:"取消",
  close:"关闭",
  modify:"修改",
  remove:"删除",
  add:"增加",
  save:"保存",
  search:"搜索",
  cmt:'备注',
  name:'名称',
  state:'状态',
  type:'类型',
  prjName:'项目',
  detail:'详情',
  createAt:'创建时间',
  sku:'存货单位',
  num:'数量',
  execAcc:'执行人',
  cfmRmv:'是否确定删除',

  sex:{
    F:'男',
    M:'女',
    U:'未知'
  },
  resState:{
    IDLE:'闲置在仓库中',
    USE:'使用中',
    DISC:'报废',
    BAD:'损坏了',
    NONE:'用完'
  },
  skuType:{
    WHL:'整机',
    PART:'零件',
    SOFT:'软件',
    VIRT:'虚拟物品'
  },
  outType:{
    OUT:'直接出库',
    DISC:'报废'
  },
  admType:{
    I:'入库',
    O:'出&入库'
  },
  grnType:{
    INN:'内部发货',
    EXT:'外部发货'
  },
  gdnType:{
    INN:'向内发货',
    EXT:'向外发货'
  },
  grnState:{
    WAIT:'等待发货',
    CHK:'正在入库',
    OVER:'已完成'
  },
  gdnState:{
    WAIT:'等待发货',
    CHK:'正在出库',
    TRAN:'运输中',
    OVER:'已完成',
    LOST:'丢失',
    BACK:'退货'
  },
  fbLevel:{
    L:'低',
    M:'中',
    H:'高',
    F:'致命'
  },
  factory:{
    title:'工厂',
    addr:'地址',
    admType:'管理员类型',
    account:'管理员帐号',
    admin:'仓库管理员'
  },
  sku:{
    title:'存货单位',
    yearDepr:'年度折旧率',
    monthDepr:'月度折旧率',
    type:'类型',
    noHead:'编号头',
    speci:'规格',
    price:'报价',
    feedback:'反馈'
  },
  supplier:{
    title:'供应商',
    creator:'创建人',
    addr:'地址',
    business:'主营业务',
    taxid:'税号'
  },
  contact:{
    title:'联系人',
    name:'姓名',
    post:'职位',
    phone:'联系电话'
  },
  storage:{
    title:'仓储管理',
    in:'入库',
    out:'出库',
    list:'资产清单',
    out_log:'异常出库记录',
    dir_in:'直接入库',
    dir_out:'直接出库',
    purchase:'采购单',
    attach:'资产挂账',
    unattach:'资产解挂',
    check:'清点',
    discard:'报废',
    inDate:'入库时间',
    outDate:'发货时间',
    expDate:'期望时间',
    cfmDate:'确认时间',
    execAcc:'执行人',
    tranNo:'运单号',
    applicant:'申请人',
    receiver:'收货人',
    checkAt:'清点时间',
    chkOk:'正常',
    chkBad:'异常',
    no:'资产编号'
  },
  purchase:{
    title:'采购',
    price:'单价',
    cost:'成本'
  },
  grn:{
    title:'入库',
    skuList:'入库列表'
  },
  gdn:{
    title:'出库',
    skuList:'出库列表',
    applyCmt:'申请人备注',
    unCfmed:'未确认'
  },
  errMsgs:{
    '6001':'存在SKU关联了供应商',
    '6002':'供应商联系人不为空',
    '6003':'仓库不为空',
    '6004':'入库清单不为空，不可以删除',
    '6005':'出库单不存在，或未启动',
    '12001':'入库资源与申请的资源不一致',
    '6008':'入库请求已完成，不可删除入库详单',
    '6009':'存量不足',
    'unknown':'未知错误'
  }
}
};