export default {
en:{
  app_name:"HR",
  ok:"OK",
  cancel:"Cancel",
  modify:"Modify",
  remove:"Delete",
  add:"Add",
  save:"Save",
  search:"Search"
},
cn:{
  app_name:"资源管理",
  ok:"确定",
  cancel:"取消",
  close:"关闭",
  modify:"修改",
  remove:"删除",
  add:"增加",
  save:"保存",
  search:"搜索",
  cmt:'备注',
  name:'名称',
  no:'资产编号',
  state:'状态',
  detail:'详情',
  createAt:'创建时间',
  sku:'存货单位',

  sex:{
    F:'男',
    M:'女',
    U:'未知'
  },
  
  skuType:{
    WHL:'整机',
    PART:'零件',
    SOFT:'软件',
    VIRT:'虚拟物品'
  },
  admType:{
    I:'入库',
    O:'出&入库'
  },
  fbLevel:{
    L:'低',
    M:'中',
    H:'高',
    F:'致命'
  },
  factory:{
    title:'工厂',
    addr:'地址',
    admType:'管理员类型',
    account:'管理员帐号',
    admin:'仓库管理员'
  },
  sku:{
    title:'存货单位',
    yearDepr:'年度折旧率',
    monthDepr:'月度折旧率',
    type:'类型',
    noHead:'编号头',
    speci:'规格',
    price:'报价',
    feedback:'反馈'
  },
  supplier:{
    title:'供应商',
    creator:'创建人',
    addr:'地址',
    business:'主营业务',
    taxid:'税号'
  },
  contact:{
    title:'联系人',
    name:'姓名',
    post:'职位',
    phone:'联系电话'
  },
  storge:{
    title:'仓储管理',
    in:'入库',
    out:'出库',
    list:'资产清单',
    check:'清点',
    inDate:'入库日期',
    outDate:'发货日期',
    expDate:'期望日期',
    cfmDate:'确认日期',
    execAcc:'执行人',
    tranNo:'运单号',
    applicant:'申请人',
    receiver:'收货人',
    checkAt:'清点日期'
  },
  purchase:{
    title:'采购',
    price:'单价',
    cost:'成本'
  },
  errMsgs:{
    '6001':'存在SKU关联了供应商',
    '6002':'供应商联系人不为空',
    '6003':'仓库不为空',
    '6004':'入库清单不为空，不可以删除',
    '6005':'出库单不存在，或未启动',
    '6006':'要发货的资产已添加，或不在发货列表中',
    '6007':'入库资源与申请的资源不一致',
    '6008':'入库请求已完成，不可删除入库详单',
    'unknown':'未知错误'
  },
}
};