export default {
en:{
  app_name:"HR",
  ok:"OK",
  modify:"Modify",
  remove:"Delete",
  add:"Add",
  search:"Search"
},
zh:{
  app_name:"财务管理",
  ok:"确定",
  close:"关闭",
  modify:"修改",
  remove:"删除",
  add:"增加",
  search:"搜索",
  cmt:'备注',
  applyAt:'申请时间',
  payAt:'支付时间',
  submitter:'申请人',
  notCfm:'未确认',
  notPaid:'未支付',
  unSet:'不指定',
  forEver:'永久',
  deduct:'扣减',
  invoice:'发票号',

  income:{
    title:'收入',
    maybeAt:'可能到账日期',
    mode:'收款方式',
    val:'金额',
    sn:'流水号',
    bank:'付款方帐号',
    cfmAcc:'确认人',
    prj:'收款项目',
    direct:'直接收款',
    alertDir:'直接收款，无法撤回，请确认是否执行?',
    state:{
      WAIT:'待确认',
      OVER:'已确认'
    }
  },
  salary:{
    title:'发薪',
    total:'总额',
    cfmAcc:'支付执行人',
    bank:'帐号信息',
    download:'下载',
    dlList:'下载列表',
    state:{
      OVER:'已发放',
      WAIT:'待发放'
    }
  },
  pay:{
    title:'支出',
    mode:'付款方式',
    val:'金额',
    sn:'流水号',
    bank:'收款方帐号',
    expectAt:'期望付款日期',
    cfmAcc:'付款执行人',
    prj:'付款项目',
    direct:'直接付款',
    alertDir:'直接付款，无法撤回，请确认是否执行?',
    state:{
      WAIT:'待付款',
      OVER:'已付款'
    }
  },
  balance:{
    title:'资产负债表',
    type:'类型',
    val:'金额(元)'
  },
  balLog:{
    title:'资产负债表操作记录',
    deducted:'已扣减',
    createAt:'添加时间',
    expireAt:'过期时间',
    type:'资产/负债类型',
    val:'金额'
  },
  bank:{
    title:'常用银行帐号',
    type:'类型',
    bank:'开户行',
    account:'银行帐号',
    name:'户名' 
  },
  balTypes:{
    CUR:{label:'流动资产',
      types:{
        CUR_CASH:'现金',
        CUR_SINV:'短期投资',
        CUR_SDEBT:'短期债权',
        CUR_SBILL:'应收票据',
        CUR_RECV:'应收账款',
        CUR_INVT:'存货',
        CUR_ACCR:'利息'
      }
    },
    FIX:{label:'固定资产',
      types:{
        FIX_EQUIP:'设备',
        FIX_LDEBT:'长期债券',
        FIX_STOCK:'股权'
      }
    },
    VIR:{label:'虚拟资产',
      types:{
        VIR_COPY:'版权',
        VIR_PATENT:'专利',
        VIR_BRAND:'品牌',
        VIR_GOODS:'虚拟物品'
      }
    },
    CDEBT:{label:'流动负债',
      types:{
        CDEBT_SHORT:'短期债',
        CDEBT_NEEDPAY:'应付账款',
        CDEBT_SBILL:'短期应付票据',
        CDEBT_SALARY:'待付工资',
        CDEBT_TAX:'应缴税费',
        CDEBT_ACCR:'应付利息',
      }
    },
    FDEBT:{label:'长期负债',
      types:{
        FDEBT_LDEBT:'长期债务',
        FDEBT_NEEDPAY:'长期应付款'
      }
    }
  },
  bankType:{
    EMPL:'雇员帐号',
    PER:'个人帐号',
    ENT:'企业帐号'
  },
  salaryType:{
    SALARY:'工资',
    SUBSIDY:'补贴',
    EXPENSE:'报销',
    BONUS:'奖金',
    SHARE:'分红',
    TAX:'个人所得税',
    SECURITY0:'劳动保障(个人)',
    SECURITY1:'劳动保障(公司)',
    OLD:'养老保险',
    MEDICARE:'医疗保险',
    JOB:'失业保险',
    INJURY:'工伤保险',
    PCREATION:'生育保险',
    HOUSE:'住房公积金'
  },
  sponTp:{
    P:"个人交",
    C:"公司交"
  },
  payMode:{
    BANK:'银行转账',
    CASH:'现金',
    WX:'微信转账',
    ALIP:'支付宝转账'
  },
  errMsgs:{
      '6001':'工时未上报，不能发薪'
  }
}
}